# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-07-03 20:14
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='File_infos',
            fields=[
                ('file_info_id', models.IntegerField(primary_key=True, serialize=False)),
                ('info', models.CharField(max_length=100)),
                ('value', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'file_infos',
            },
        ),
        migrations.CreateModel(
            name='Files',
            fields=[
                ('file_id', models.IntegerField(primary_key=True, serialize=False)),
                ('path', models.CharField(max_length=200)),
                ('mimetype', models.CharField(max_length=60)),
                ('deletable', models.IntegerField()),
                ('newfile', models.BooleanField()),
                ('searchDone', models.IntegerField()),
            ],
            options={
                'db_table': 'files',
            },
        ),
        migrations.CreateModel(
            name='Folders',
            fields=[
                ('folder_id', models.IntegerField(primary_key=True, serialize=False)),
                ('folder', models.CharField(max_length=200)),
            ],
            options={
                'db_table': 'folders',
            },
        ),
        migrations.CreateModel(
            name='Movie_infos',
            fields=[
                ('info_id', models.IntegerField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=100)),
                ('casting', models.CharField(max_length=100)),
                ('productionYear', models.CharField(max_length=4)),
                ('description', models.CharField(max_length=1000)),
                ('poster', models.CharField(max_length=100)),
                ('posterUrl', models.CharField(max_length=100)),
                ('descriptionFile', models.CharField(max_length=100)),
                ('thumbnail', models.CharField(max_length=100)),
                ('rating', models.FloatField()),
                ('file', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='frontend.Files')),
            ],
            options={
                'db_table': 'movie_infos',
            },
        ),
        migrations.AddField(
            model_name='files',
            name='display_folder',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='display_folder_id', to='frontend.Folders'),
        ),
        migrations.AddField(
            model_name='files',
            name='location_folder',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='location_folder_id', to='frontend.Folders'),
        ),
        migrations.AddField(
            model_name='file_infos',
            name='file',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='frontend.Files'),
        ),
    ]
