# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-07-08 09:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0003_auto_20180708_0857'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movie_infos',
            name='category',
        ),
        migrations.AddField(
            model_name='files',
            name='virtualPath',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.DeleteModel(
            name='Category',
        ),
    ]
